- name: Dokumentacja ról usługi Azure AD
  href: index.yml
- name: Omówienie
  items:
    - name: Role usługi Azure AD
      href: custom-overview.md
- name: Przewodniki Szybki start
  items:
    - name: Tworzenie nieograniczonej liczby rejestracji aplikacji
      href: quickstart-app-registration-limits.md
- name: Samouczki
  items:
    - name: Tworzenie grupy dynamicznej
      href: /azure/active-directory/enterprise-users/users-revoke-access
- name: Pojęcia
  expanded: true
  items:
    - name: Delegowanie ról administratorów usługi Azure AD
      href: concept-delegation.md
    - name: Porównywanie domyślnych uprawnień użytkowników
      href: /azure/active-directory/fundamentals/users-default-permissions
    - name: Porównanie ról na platformie Azure i w usłudze Azure AD
      href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Informacje o jednostkach administracyjnych w usłudze Azure AD
      href: administrative-units.md
- name: Przewodniki z instrukcjami
  expanded: true
  items:
    - name: Użytkownicy i role
      items:
        - name: Przypisywanie użytkowników do ról administratorów
          href: /azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal
        - name: Odwoływanie dostępu użytkownika
          href: /azure/active-directory/enterprise-users/users-revoke-access
        - name: Przypisywanie roli do użytkownika-gościa
          href: /azure/active-directory/b2b/add-guest-to-role?context=azure/active-directory/roles/context/ugr-context
        - name: Ograniczanie dostępu użytkowników-gości
          href: /azure/active-directory/enterprise-users/users-restrict-guest-permissions?context=azure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Grupy dynamiczne i goście
          href: /azure/active-directory/b2b/use-dynamic-groups?context=azure/active-directory/roles/context/ugr-context
    - name: Role i uprawnienia
      expanded: true
      items:
        - name: Role i uprawnienia
          href: permissions-reference.md
        - name: Wyświetlanie i przypisywanie ról
          href: manage-roles-portal.md
        - name: Delegowanie mojego personelu
          href: my-staff-configure.md
    - name: Role niestandardowe
      expanded: true
      items:
        - name: Omówienie ról niestandardowych
          href: custom-overview.md
        - name: Tworzenie roli niestandardowej
          href: custom-create.md
        - name: Wyświetlanie przypisań ról niestandardowych
          href: custom-view-assignments.md
        - name: Przypisywanie ról niestandardowych w witrynie Azure Portal
          href: /azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal
        - name: Przypisywanie ról niestandardowych w programie PowerShell
          href: custom-assign-powershell.md
        - name: Przypisywanie ról niestandardowych na potrzeby aplikacji dla przedsiębiorstw
          href: custom-enterprise-apps.md
        - name: Uprawnienia ról niestandardowych
          items:
            - name: Uprawnienia rejestracji aplikacji
              href: custom-available-permissions.md
            - name: Uprawnienia aplikacji dla przedsiębiorstw
              href: custom-enterprise-app-permissions.md
            - name: Uprawnienia dotyczące zgód aplikacji
              href: custom-consent-permissions.md
        - name: Delegowanie roli administratora aplikacji
          href: delegate-app-roles.md
    - name: Przypisywanie ról do grup
      items:
        - name: Wersja zapoznawcza przypisywania ról na podstawie grup
          href: groups-concept.md
        - name: Tworzenie grupy z możliwością przypisania do roli
          href: groups-create-eligible.md
        - name: Przypisywanie ról do grupy
          href: groups-assign-role.md
        - name: Usuwanie przypisań ról z grupy
          href: groups-remove-assignment.md
        - name: Wyświetlanie przypisań ról grupy
          href: groups-view-assignments.md
        - name: Ustawianie grupy jako kwalifikującej się do roli w usłudze PIM
          href: groups-pim-eligible.md
        - name: Często zadawane pytania i rozwiązywanie problemów
          href: groups-faq-troubleshooting.md
    - name: Zabezpieczanie ról
      items:
        - name: Planowanie zabezpieczeń roli
          href: security-planning.md
        - name: Tworzenie kont awaryjnych
          href: security-emergency-access.md
    - name: Jednostki administracyjne
      items:
        - name: Omówienie jednostek administracyjnych
          href: administrative-units.md
        - name: Dodawanie i zarządzanie
          href: admin-units-manage.md
        - name: Dodawanie użytkowników i zarządzanie nimi
          href: admin-units-add-manage-users.md
        - name: Dodawanie grup i zarządzanie nimi
          href: admin-units-add-manage-groups.md
        - name: Przypisywanie roli z zakresem
          href: admin-units-assign-roles.md
        - name: Często zadawane pytania i rozwiązywanie problemów
          href: admin-units-faq-troubleshoot.md
    - name: Rozwiązywanie problemów
      items:
        - name: Uzyskiwanie pomocy technicznej dla usługi Azure AD
          href: /azure/active-directory/fundamentals/active-directory-troubleshooting-support-howto
- name: Dokumentacja
  items:
    - name: Najmniej uprzywilejowane role według zadania
      href: delegate-by-task.md
    - name: Dokumentacja ról platformy Microsoft 365
      href: m365-workload-docs.md
    - name: Interfejs API programu Graph
      href: /graph/api/resources/azure-ad-overview?view=graph-rest-1.0
    - name: Interfejs wiersza polecenia usługi Azure AD
      href: /cli/azure/ad
    - name: Moduł Azure AD PowerShell dla programu Graph
      href: /powershell/azure/active-directory/install-adv2?view=azureadps-2.0
    - name: Limity usługi Azure AD
      href: /azure/active-directory/enterprise-users/directory-service-limits-restrictions