### YamlMime:Landing
title: Platforma Kubernetes z usługą Azure Arc (wersja zapoznawcza)
summary: Dowiedz się, jak zarządzać klastrami Kubernetes przy użyciu usługi Azure Arc
metadata:
  title: Platforma Kubernetes z usługą Azure Arc
  description: Dowiedz się, jak zarządzać komputerami lokalnymi na platformie Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: a305e50287187292b2a1b9c90b1e6dee98baf75b
  ms.sourcegitcommit: 829d951d5c90442a38012daaf77e86046018e5b9
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 10/09/2020
  ms.locfileid: "91824160"
landingContent:
- title: Łączenie klastrów Kubernetes z platformą Azure przy użyciu usługi Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Co to jest platforma Kubernetes z włączoną usługą Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Połączenie klastra
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Wdrażanie konfiguracji przy użyciu metodyki GitOps
      url: use-gitops-connected-cluster.md
    - text: Wdrażanie elementów chart programu Helm przy użyciu metodyki GitOps
      url: use-gitops-with-helm.md
    - text: Wymuś metodykę GitOps przy użyciu usługi Azure Policy
      url: use-azure-policy.md
    - text: Wdrażanie obciążeń usługi Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Architektura referencyjna
  linkLists:
  - linkListType: architecture
    links:
    - text: Zarządzanie wdrożeniami i konfiguracjami dla hybrydowych klastrów Kubernetes
      url: /architecture/hybrid/arc-hybrid-kubernetes
